openapi: 3.0.3
info:
  title: Purchasing Impact API
  version: "1.0"
  description: |
    Purchase trees or carbon avoidance credits directly from your application or service with our JSON impact API. You simply tell our API how many trees or credits you would like to buy. Any purchases made via the API will be billed on the 1st of every month, with impact applied following successful payment.

    If you’d like to create a subscription-free account, head to: https://ecologi.com/pay-as-you-go. With an account you can find your API key on the 'Impact API' page.

    There is a billing minimum of 25 trees or 1 tonne of carbon avoidance. If you have purchased less than either of these thresholds since your most recent invoice, your impact will roll over to next month's invoice.

    Click on the "Endpoints" menu item on the left to read more about the APIs for purchasing trees and carbon avoidance credits.
servers:
  - url: "https://public.ecologi.com"
    description: Production
paths:
  /impact/trees:
    post:
      summary: Purchase trees
      operationId: create-impact-trees
      description: Use this endpoint to purchase 1 or more trees per request
      security:
        - API Key: []
      requestBody:
        description: |-
          Send a JSON body object with key "number" and a value equalling the number of trees to plant in your forest for this request. You can optionally add a "name" key, which will be shown when you view the trees in your Ecologi forest.

          If your Ecologi profile is public, any personally identifiably information sent in the "name" field (ie. the name of your customer) will also be visible publicily, and therefore you should ask for permission before sending it to us, or shield the user by only sending their first name for example.

          If multiple requests are made to plant trees with the same name within 24hrs, they will accumulate on a single tile. If you would like to avoid this you can provide a different name value like maybe adding the first letter of the surname to the next lot or space the requests greater than 24hrs apart.

          Passing "test: true" will return the anticipated response, but you will not be charged for these trees, nor will they show in your Ecologi profile forest.
        content:
          application/json:
            schema:
              description: ""
              type: object
              properties:
                number:
                  type: number
                  minimum: 1
                  maximum: 250000
                  description: The number of trees to purchase
                name:
                  type: string
                  minLength: 1
                  example: Elijah Wood
                  description: The "funded by" name for these trees
                test:
                  type: boolean
                  description: Whether this is a test transaction or not
              required:
                - number
            examples:
              Buy trees (live):
                value:
                  number: 2
              Buy trees (test):
                value:
                  number: 2
                  test: true
              Buy trees with name (test):
                value:
                  number: 2
                  name: Alex's trees
                  test: true
      responses:
        "201":
          content:
            application/json:
              schema:
                description: ""
                type: object
                properties:
                  amount:
                    type: number
                    example: 0.38
                    description: The total cost of this transaction
                  currency:
                    type: string
                    enum:
                      - GBP
                      - USD
                      - EUR
                      - CAD
                      - AUD
                    example: GBP
                    description: The currency of the amount
                  treeUrl:
                    type: string
                    example: "https://ecologi.com/test?tree=604a74856345f7001caff578"
                    description: The URL for the trees you just planted
                  name:
                    type: string
                    example: Elijah Wood
                    description: The name you passed in the request body
                  projectDetails:
                    type: array
                    items:
                      properties:
                        name:
                          type: string
                        projectUrl:
                          type: string
                        splitPercentage:
                          type: number
                        splitAmountTrees:
                          type: number
                required:
                  - amount
                  - currency
                  - treeUrl
              examples:
                3 trees purchased:
                  value:
                    amount: 0.38
                    currency: GBP
                    treeUrl: "https://ecologi.com/test?tree=604a74856345f7001caff578"
                    name: Alex's trees
                    projectDetails:
                      - name: "Forest restoration in Kenya"
                        projectUrl: "https://ecologi.com/projects/forest-restoration-in-kenya"
                        splitPercentage: 100
                        splitAmountTrees: 3
          description: "If your request is successful you’ll receive a JSON object containing information about your purchase. Including the amount it cost, the currency billed, the name (if passed in the request), the URL of the pending tree in your Ecologi profile forest and details of the associated projects."
      parameters:
        - schema:
            type: string
          in: header
          name: "Idempotency-Key"
          description: This random request key allows you to safely retry requests without accidentally performing the same operation twice.
    parameters: []
  /impact/carbon:
    post:
      summary: Purchase carbon avoidance
      operationId: post-impact-carbon
      responses:
        "201":
          description: "If your request is successful you’ll receive a JSON object containing information about your purchase. Including the amount it cost, the currency billed, the number and unit of the purchase, converted tonnes amount and details of the associated projects."
          content:
            application/json:
              schema:
                description: ""
                type: object
                properties:
                  number:
                    type: number
                    description: The number of units you purchased
                  units:
                    type: string
                    enum:
                      - KG
                      - Tonnes
                    description: The type of purchase you made (KG/Tonnes)
                  numberInTonnes:
                    type: number
                    minimum: 0.001
                    description: The number of units you purchased converted to tonnes
                  amount:
                    type: number
                    example: 7.4
                    description: The total cost of this transaction
                  currency:
                    type: string
                    enum:
                      - GBP
                      - USD
                      - EUR
                      - CAD
                      - AUD
                    description: The currency of the amount
                  projectDetails:
                    type: array
                    items:
                      properties:
                        name:
                          type: string
                        projectUrl:
                          type: string
                        splitPercentage:
                          type: number
                        splitAmountTonnes:
                          type: number
                required:
                  - number
                  - units
                  - numberInTonnes
                  - amount
                  - currency
              examples:
                10KG Transaction response:
                  value:
                    number: 10
                    units: KG
                    numberInTonnes: 0.01
                    amount: 37
                    currency: GBP
                    projectDetails:
                      - name: Peatland restoration and conservation in Indonesia
                        projectUrl: https://ecologi.com/projects/peatland-restoration-in-indonesia
                        splitPercentage: 14,
                        splitAmountTonnes: 0.0014
                      - name: Converting landfill gas to energy in Northern Turkey
                        projectUrl: https://ecologi.com/projects/converting-landfill-gas-to-energy-turkey
                        splitPercentage: 86,
                        splitAmountTonnes: 0.0086
      description: Use this endpoint to purchase 1 or more kilogram of carbon avoidance credits per request
      security:
        - API Key: []
      parameters:
        - schema:
            type: string
          in: header
          name: "Idempotency-Key"
          description: This random request key allows you to safely retry requests without accidentally performing the same operation twice.
      requestBody:
        content:
          application/json:
            schema:
              description: ""
              type: object
              properties:
                number:
                  type: number
                  example: 0
                  description: The number of units to purchase
                units:
                  type: string
                  enum:
                    - KG
                    - Tonnes
                  description: The type of purchase to make (KG/Tonnes)
                test:
                  type: boolean
                  description: Whether this is a test transaction or not
              required:
                - number
                - units
            examples:
              Buy credits (live):
                value:
                  number: 10
                  units: KG
              Buy credits (test):
                value:
                  number: 10
                  units: KG
                  test: true
        description: |-
          Send a JSON body object with both "units" and "number" keys for a valid request.

          "units" tells the API that you wish to purchase credits by the kilogram or tonne.

          "number" should be the value equaling the number of units of carbon credits to purchase for this request.

          Passing "test: true" will return the anticipated response, but you will not be charged for the credits, nor will they show on your Ecologi profile.

          Note: the smallest valid amount to purchase is 1kg. If you're using the "Tonnes" unit, 0.001 is the minimum value.
components:
  securitySchemes:
    API Key:
      type: http
      scheme: bearer
      description: 'To authorise your requests, send the "Authorization" header along with an API key using the "Bearer" format.'
